dist: trusty
sudo: required
language: ruby
matrix:
  include:
    - rvm: 2.3.3
      jdk: oraclejdk8

    - rvm: 2.2.6
      jdk: oraclejdk8

    - rvm: 2.4.2
      jdk: oraclejdk8

before_install:
  - gem update --system
  - gem --version
  - gem install bundler -v 1.14.3
  - bundle version
  - curl -sS https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.tar.gz | tar xz -C /tmp

install:
  - bundle install

script:
  - make test
